[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sendgrid/mail"]
  directory = "netlify/functions"

[build]
  command = "echo Build step not required"
  publish = "dist"

[[redirects]]
from = "/.netlify/functions/submit-booking"
to = "/.netlify/functions/submit-booking-2-0"
status = 200
force = true
